name: homebased_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.5
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.0
  uuid: ^4.0.0
  path: ^1.8.3
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  flutter_svg: ^2.2.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  path_provider: ^2.1.5

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - .env
